apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      # Init container to wait for Kafka DNS
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command:
          - sh
          - -c
          - |
            until nslookup kafka-0.kafka-headless.kafka.svc.cluster.local; do
              echo "Waiting for Kafka DNS..."
              sleep 5
            done
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:latest
        args:
          - '--kafka.server=kafka-0.kafka-headless.kafka.svc.cluster.local:9092'
        ports:
        - containerPort: 9308
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: kafka
spec:
  selector:
    app: kafka-exporter
  ports:
  - name: metrics
    port: 9308
    targetPort: 9308