name: CI - Kind Local K8S Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  kind-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Kind + Kubectl
        run: |
          # Install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

          # Install Kind
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

          # Verify versions
          kind --version
          kubectl version --client

      - name: Create Kind Cluster
        run: |
          kind create cluster --name ci-pipeline --config ./configs/kind-config.yaml
          kubectl cluster-info

      - name: Create Namespaces for kafka and montoring
        run: |
         kubectl apply -f namespace/namespace.yaml
         kubectl get namespace kafka monitoring

      - name: Deploy Kafka and Monitoring
        run: |
          # Kafka & Kafka Exporter   
          kubectl apply -f kafka/kafka-cluster.yaml
          kubectl apply -f kafka/kafka-exporter.yaml

          kubectl wait --for=condition=Available statefulset/kafka -n kafka --timeout=180s
          kubectl wait --for=condition=Available deployment/kafka-exporter -n kafka --timeout=180s
          
          # Prometheus & Grafana 
          kubectl apply -f monitoring/prometheus-deployment.yaml
          kubectl apply -f monitoring/prometheus-service.yaml
          kubectl apply -f monitoring/grafana-deployment.yaml
          kubectl apply -f monitoring/grafana-service.yaml
          

      - name: Verify Kafka
        run: |
            # Show pod status instead of waiting
            kubectl get pods -n kafka -o wide

      - name: Verify Prometheus & Grafana 
        run: |
            # Show pod status
            kubectl get pods -n monitoring -o wide

      - name: List K8S Cluster and Clean Up
        run: |
            kind get clusters 
            kind delete cluster --name kind-local-k8s
            kind get clusters 